### ISSUE TITLE
Website is not available after installation and configuration

### ISSUE THREAD

**Issue by Hunt3rle** [EricAndrechek/homebridge-display#139]
**Describe the bug**
Website is not available after installation and configuration

**Expected behavior**
After installation via config-ui-x and configuration it is not possible to open the generated website via browser (pc/raspi/ipad)

**Homebridge Server (please complete the following information):**
 - Raspberry Pi 4
 - NodeJS Version [e.g. v14.16.0]
 - Homebride-Display Version [installed today]

**Display Client (please complete the following information):**
 - Device: [e.g. iPad Air3, PC, Raspi4]
 - OS: [e.g. iOS14.4.1
 - Browser [Safari, Chromium]

**Screenshots**
not available

**Comment by EricAndrechek** [comment]
To properly diagnose this issue, I will need a bit more information from you. Can you confirm for me you are:
- Connecting to the IP address of your homebridge server rather than going to homebridge.local? There are known issues of it failing to connect through a custom hostname, so please look in the config-ui-x dashboard for the IP address and then go to `http://ipaddresshere:6969` replacing the last 4 numbers there with whatever custom port you set in homebridge-display settings (default is 6969).
- Not using more than one of the same widget (with the exception of the blank widget). This means that you can only have one accessory widget on your screen at a time.
- Any and all widgets that you are using have their respective optional form fields in the bottom filled out.
- Insecure mode turned on if you are attempting to use the accessory widget.

If all of the above is confirmed to be correct then please attach:
- The debug logs from your homebridge server by turning on debugging mode and then copying/saving the logs.
- A copy of your config.json for homebridge-display and for the main settings of your homebridge server.
(Please be sure to remove any confidential information such as API keys from your logs and configs before uploading them)


Apologies for the inconvenience, hopefully we can get this working!

**Comment by Hunt3rle** [comment]
Hello Eric,

 

ok that was my failure: „Not using more than one of the same widget“

 

I only want to use it with clock and Accessorires. J

 

Thx for your help

 

Dirk

 

Von: Eric Andrechek ***@***.***> 
Gesendet: Sonntag, 14. März 2021 22:26
An: EricAndrechek/homebridge-display ***@***.***>
Cc: Hunt3rle ***@***.***>; Author ***@***.***>
Betreff: Re: [EricAndrechek/homebridge-display] Website is not available after installation and configuration (#139)

 

To properly diagnose this issue, I will need a bit more information from you. Can you confirm for me you are:

*	Connecting to the IP address of your homebridge server rather than going to homebridge.local? There are known issues of it failing to connect through a custom hostname, so please look in the config-ui-x dashboard for the IP address and then go to http://ipaddresshere:6969 replacing the last 4 numbers there with whatever custom port you set in homebridge-display settings (default is 6969).
*	Not using more than one of the same widget (with the exception of the blank widget). This means that you can only have one accessory widget on your screen at a time.
*	Any and all widgets that you are using have their respective optional form fields in the bottom filled out.
*	Insecure mode turned on if you are attempting to use the accessory widget.

If all of the above is confirmed to be correct then please attach:

*	The debug logs from your homebridge server by turning on debugging mode and then copying/saving the logs.
*	A copy of your config.json for homebridge-display and for the main settings of your homebridge server.
(Please be sure to remove any confidential information such as API keys from your logs and configs before uploading them)

Apologies for the inconvenience, hopefully we can get this working!

**Comment by EricAndrechek** [comment]
Glad to hear! I am hoping to fix that in one of the next few releases.

**Comment by Hunt3rle** [comment]
Is there actually a way to control which accessories you want to display?

 

 

Von: Eric Andrechek ***@***.***> 
Gesendet: Montag, 15. März 2021 05:49
An: EricAndrechek/homebridge-display ***@***.***>
Cc: Hunt3rle ***@***.***>; Author ***@***.***>
Betreff: Re: [EricAndrechek/homebridge-display] Website is not available after installation and configuration (#139)

 

Glad to hear! I am hoping to fix that in one of the next few releases.

**Comment by EricAndrechek** [comment]
As of right now, no. It only shows the first few accessories it registers, but that and adding the ability for more accessories appearing is my top priority right now.

**Comment by Hunt3rle** [comment]
Perfect! J Thx

 

Von: Eric Andrechek ***@***.***> 
Gesendet: Montag, 15. März 2021 05:53
An: EricAndrechek/homebridge-display ***@***.***>
Cc: Hunt3rle ***@***.***>; Author ***@***.***>
Betreff: Re: [EricAndrechek/homebridge-display] Website is not available after installation and configuration (#139)

 

As of right now, no. It only shows the first few accessories it registers, but that and adding the ability for more accessories appearing is my top priority right now.
